spring.application.name=VMWatch

#DB Properties
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=local
#spring.datasource.username=admin
#spring.datasource.password=Password
#spring.datasource.url=jdbc:postgresql://DB:5432/vmwatch